# Generated by Django 3.0.2 on 2020-12-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBMAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
