# Generated by Django 3.0.2 on 2020-12-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBMAPP', '0003_implinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implinks',
            name='link_url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
