# Generated by Django 3.0.2 on 2020-12-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBMAPP', '0004_auto_20201231_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implinks',
            name='link_url',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
