# Generated by Django 3.0.2 on 2020-12-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBMAPP', '0005_auto_20210101_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(max_length=1000)),
                ('link_url', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('featured', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='implinks',
            name='link_url',
            field=models.CharField(max_length=1000),
        ),
    ]
