# Generated by Django 3.1.5 on 2021-01-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBMAPP', '0008_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='featured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
