# Generated by Django 3.1.5 on 2021-01-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBMAPP', '0010_auto_20210106_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tender',
            name='title',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='title',
            field=models.TextField(max_length=20),
        ),
    ]
