# Generated by Django 3.1.5 on 2021-01-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBMAPP', '0011_auto_20210106_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='link_url',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='link_url',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='link_url',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tender',
            name='link_url',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tender',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
