# Generated by Django 3.1.5 on 2021-01-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBMAPP', '0012_auto_20210107_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
