# Generated by Django 3.1.5 on 2021-01-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBMAPP', '0013_auto_20210107_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(max_length=100)),
                ('address_txt', models.TextField()),
                ('address_link', models.URLField()),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
