# Generated by Django 3.1.5 on 2021-01-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBMAPP', '0014_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='college',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
